In [1]:
import numpy as np

In [2]:
a = np.empty([4,5])

In [3]:
a[1:3,2] = [3,4]

In [4]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
import random
[random.randint(1,4) for i in range(4)]

[1, 2, 3, 1]

In [7]:
quality = [random.randint(1,4) for i in range(10)]

In [13]:
np.array([quality])

array([[2, 4, 3, 2, 1, 4, 2, 4, 1, 3]])

In [14]:
np.apply_along_axis(lambda x:2500 - (x-1)*350, 1, np.array([quality]))

array([[2150, 1450, 1800, 2150, 2500, 1450, 2150, 1450, 2500, 1800]])